# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pylibjpeg-openjpeg
  version: "2.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pylibjpeg_openjpeg-${{ version }}.tar.gz
  sha256: e0ea4d9e59820b02c8437121ae65cc28e98d9e9150f4a6967f2c3ba805e7f873

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - cmake
    - lcms2
    - libpng
    - libtiff
    - make
    - pkgconfig
    - zlib
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - cython >=3.0.10
    - numpy >=2.0.0,<3.0.0
    - pip
    - poetry-core >=1.8,<2
    - python
    - setuptools
  run:
    - cython >=3.0.10
    - numpy >=2.0.0,<3.0.0
    - python
  ignore_run_exports:
    by_name:
      - cython
      - numpy
      - python

tests:
  - python:
      imports:
        - openjpeg
  - requirements:
      run:
        - cython >=3.0.10
        - pip
        - python
    script:
      - pip check

about:
  homepage: https://github.com/pydicom/${{ name }}
  license: BSD-3-Clause AND MIT AND BSD-2-Clause
  license_file:
    - LICENSE
    - lib/openjpeg/LICENSE
    - lib/openjpeg/thirdparty/liblcms2/COPYING
    - lib/openjpeg/thirdparty/libpng/LICENSE
    - lib/openjpeg/thirdparty/astyle/LICENSE.md
    - lib/openjpeg/src/bin/wx/OPJViewer/source/license.txt
  summary: A Python wrapper for openjpeg, with a focus on use as a plugin for for pylibjpeg

extra:
  recipe-maintainers:
    - psadil
    - scaramallion
